name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f302f085071e004293088ef30591f973b7ea5336eee20532be13bddb94072d4"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
