name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10af4928f053bccd402e5f33bca21e04f0daea27e0fb9144b57f467430d97c4f"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
