name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d85938418eff5614e9940d40f44de64da8a54dc664c28fdb74433767dc4faaec"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
